### ISSUE TITLE
请问CSE 365还在更新吗?

### ISSUE THREAD

**Issue by TephrocactusMYC** [c01dkit/tech-blog#1]
啊啊啊！我也在做CSE 365 ,但是是个小白，很多关过不去，不知道大佬还在更新CSE365 SP23吗？我目前几个模块都做了大概一半，有几个卡住的看了大佬的wp会做了，不知道剩下的大佬还在做吗！

**Comment by c01dkit** [comment]
@TephrocactusMYC 感谢关注！最近以来杂活有点多，也缺少主动学习的动力，所以pwn college做了一个module就没往下做了2333 剩下的最近也打算陆陆续续启动，不过我自己也比较菜可能会更新慢一点哈哈哈 欢迎交流！

**Comment by TephrocactusMYC** [comment]
好耶好耶！欢迎交流，我也开源一下自己的部分解答hhh!
